global
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main *:80
    use_backend                 es_https

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend es_backend
    balance     roundrobin
    server  app1 10.1.1.1:80 check
    server  app2 10.1.2.1:80 check
    server  app3 10.1.3.1:80 check

backend es_https
    balance     roundrobin
    server  app1 10.1.1.1:443 check ssl verify none
    server  app2 10.1.2.1:443 check ssl verify none
    server  app3 10.1.3.1:443 check ssl verify none
